version: '3.7'

services:
  app:
    build: .
    container_name: php-container
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'joyjet_users'
      MYSQL_USER: 'joyjet'
      MYSQL_PASSWORD: 'joyjet123'
      MYSQL_ROOT_PASSWORD: 'joyjet123'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
